### ISSUE TITLE
Changing the text

### ISSUE THREAD

**Issue by millenseer** [androdlang/InfoTicker#1]
Very nice and smooth scrolling display! Thanks for that!
Your example with the abc[]-array is static and has some true magic in the callback I clearly don't understand. :-)

Imagine I get a string from an MQTT-Server publishing channel. 
How would I re-init the Ticker and give it this new string to display?

I intend to use Squix' frames for standard UI output.
Once there is an incoming message from MQTT, I disable the frames with ui.disableAutoTransition(), display the MQTT-Text and later on re-init the ui using ui.enableAutoTransition(). 
The part "display MQTT-Text" shall be replaced using your scrolling functions, as the text often is longer than the screen can display.

I believe your ticker might also require a infoTicker.stop() and infoTicker.start() function for my purpose, no?

**Comment by androdlang** [comment]
@millenseer I'm using the infoTicker to display live RSS feeds and this szenario should work for displaying MQTT messages as well in the same fashion. Let me explain a bit more: the logic to handle the messages to display is up to you and has to be implemented in a callback function which is triggerd in your main loop by calling infoTicker.tick(). A start and stop makes no sence here because you're already controlling this fuction with tick().
The idea is following: once you've provided a text to display, infoTicker handles all things to scroll this text  fully through the display and when it's finished, you'll get called and you decide what to do next. Notice, that when your callback is called, the displayed tickerline is fully cleared! Several options you can do here, either provide the same, another or empty text, or just stop calling the  tick function. 
In my RSS szenario a timer handles the incoming RSS feeds and copies the messages to an array. The infoTicker cycles all the time trough this array.

**Comment by millenseer** [comment]
Thanks for bearing with me!

Is it possible to see your live-RSS-Ticker as an example?
I am still slightly overwhelmed by how to change the text.
The callback provided in the example is a good start for the obfuscated C contest :-)
Can you please provide an example using a function as callback, not an inline pointer?

**Comment by androdlang** [comment]
sure, I provided the source in the examples folder. You have to follow following line (callbak) : `timer.setInterval(300000,handleRss);`

**Comment by marsrakete** [comment]
Thank you very much. Very interesting code. I guess, I can manage from now.
